# Generated by Django 5.1.6 on 2025-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
