# Generated by Django 5.1.6 on 2025-02-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='author',
            new_name='authors',
        ),
    ]
