# Generated by Django 5.1.6 on 2025-03-03 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_author_booktable_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
