# Generated by Django 5.1.6 on 2025-03-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_booktable_book_sr_no_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='booktable',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booktable',
            name='rating_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrow',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
