# Generated by Django 5.1.6 on 2025-03-19 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_comment_delete_like_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='available',
        ),
        migrations.AddField(
            model_name='booktable',
            name='available_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booktable',
            name='total_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 26)),
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
