# Generated by Django 5.1.6 on 2025-03-17 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_booktable_rating_remove_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='rating_sum',
        ),
        migrations.AddField(
            model_name='booktable',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
