# Generated by Django 5.1.6 on 2025-03-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_remove_booktable_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='book_sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
