# Generated by Django 5.1.6 on 2025-03-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_borrowrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='return_date',
        ),
    ]
