# Generated by Django 5.1.6 on 2025-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_booktable_book_sr_no_alter_borrow_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='book_sr_no',
            field=models.IntegerField(unique=True),
        ),
    ]
