# Generated by Django 5.1.6 on 2025-03-05 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_borrowrecord_is_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='booktable',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
